version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - wait-for-db

  wait-for-db:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache postgresql-client && 
        until pg_isready -h ${DB_HOST} -p 5432; do 
          echo waiting for db...; 
          sleep 2; 
        done
      "
    depends_on: []
    restart: "no"

volumes:
  n8n_data:
